main:
  - name: Bio
    url: /
    weight: 10
  - name: Job Market Paper
    url: /#job-market-paper
    weight: 20
  - name: Working Papers
    url: /#working-papers
    weight: 30
  - name: Work in Progress
    url: /#work-in-progress
    weight: 40
  - name: Conference Publications
    url: /#conference-publications
    weight: 50
  - name: Teaching
    url: /#teaching
    weight: 60
